ALTER TABLE users ADD COLUMN title VARCHAR(100);
ALTER TABLE users ADD COLUMN bio VARCHAR(500);
ALTER TABLE users ADD COLUMN tagline_mission VARCHAR(250);
ALTER TABLE users ADD COLUMN website VARCHAR(100);
ALTER TABLE users ADD COLUMN city VARCHAR(250);
ALTER TABLE users ADD COLUMN country VARCHAR(250);
ALTER TABLE users ADD COLUMN onboardingCompleted boolean;
